# Generated by Django 2.0.13 on 2020-02-01 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='precioVenta',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=18),
            preserve_default=False,
        ),
    ]
