# Generated by Django 3.0.4 on 2020-03-28 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0002_articulo_precioventa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='condIva',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='almacen.CondIvaOp'),
        ),
    ]
