# Generated by Django 3.0.4 on 2020-03-28 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0003_auto_20200328_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='familia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='almacen.Familia'),
        ),
    ]
